// <auto-generated />
using IPQuest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IPQuest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921065908_SeedQuizQuestions")]
    partial class SeedQuizQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IPQuest.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "A song"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "A company logo"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "A new machine"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "A secret recipe"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "The creator"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Every person who hears it"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "The nearest shop"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Nobody"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Copying a protected work without permission"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Creating your own drawing"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Writing your own story"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Making your own music"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "A brand or source of goods or services"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "A secret password"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "A computer program"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "A private diary"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "™"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "©"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "₹"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "#"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "A brand name or logo"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "A secret business formula"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "A scientific discovery"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "A personal password"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "An invention"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "A company slogan only"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "A person's nickname"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "A school timetable"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "New and inventive"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Already copied"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Kept only in a notebook"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "A brand name"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "A new technical device"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "A common word"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "A company color alone"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "A person's signature"
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "Confidential business information with value"
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "A public advertisement"
                        },
                        new
                        {
                            Id = 39,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "A school uniform"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "A public website"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "A secret recipe"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "A public logo"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "A published book"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "A public advertisement"
                        },
                        new
                        {
                            Id = 45,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = "Keeping the information confidential"
                        },
                        new
                        {
                            Id = 46,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Publishing it online"
                        },
                        new
                        {
                            Id = 47,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Sharing it publicly"
                        },
                        new
                        {
                            Id = 48,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Posting it on social media"
                        });
                });

            modelBuilder.Entity("IPQuest.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Which of these is usually protected by copyright?",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            Text = "Who generally owns copyright in an original song created by a person?",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 3,
                            Text = "Which action may violate copyright?",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 4,
                            Text = "What does a trademark mainly help identify?",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 5,
                            Text = "Which symbol is commonly associated with an unregistered trademark?",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 6,
                            Text = "Which of these can be protected as a trademark?",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 7,
                            Text = "What does a patent protect?",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 8,
                            Text = "What is an invention generally required to be for patent protection?",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 9,
                            Text = "Which of these could potentially be patented?",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 10,
                            Text = "What is a trade secret?",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 11,
                            Text = "Which of these could be a trade secret?",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 12,
                            Text = "What is important for keeping a trade secret protected?",
                            TopicId = 4
                        });
                });

            modelBuilder.Entity("IPQuest.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Protects original creative works such as books, music, videos, and artwork.",
                            Icon = "©",
                            Title = "Copyright"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Protects brand names, logos, symbols, and other identifiers.",
                            Icon = "™",
                            Title = "Trademark"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Protects new inventions and innovative technical solutions.",
                            Icon = "⚙",
                            Title = "Patent"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Protects valuable confidential business information and know-how.",
                            Icon = "🔐",
                            Title = "Trade Secret"
                        });
                });

            modelBuilder.Entity("IPQuest.Models.AnswerOption", b =>
                {
                    b.HasOne("IPQuest.Models.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("IPQuest.Models.Question", b =>
                {
                    b.HasOne("IPQuest.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("IPQuest.Models.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
