// <auto-generated />
using IPQuest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IPQuest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IPQuest.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Protects original creative works such as books, music, videos, and artwork.",
                            Icon = "©",
                            Title = "Copyright"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Protects brand names, logos, symbols, and other identifiers.",
                            Icon = "™",
                            Title = "Trademark"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Protects new inventions and innovative technical solutions.",
                            Icon = "⚙",
                            Title = "Patent"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Protects valuable confidential business information and know-how.",
                            Icon = "🔐",
                            Title = "Trade Secret"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
